# Generated by Django 3.2.3 on 2021-05-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210516_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='ingredient', through='recipes.RecipeIngredient', to='recipes.Ingredient', verbose_name='Используемые ингредиеты'),
        ),
    ]
